[package]
name = "comp_prog_lib_rs"
version = "0.1.0"
authors = ["ikanago <ikanago-dev@protonmail.com>"]
edition = "2021"

[dependencies]
num = "0.4.1"
proconio = "0.4.5"
rand = "0.8.5"

[dev-dependencies]
proptest = "1.4.0"
