name: Unit Test

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        # Skip on pull requests created by renovate because these PRs occupies the cache volume.
        if: github.actor != 'renovate[bot]'
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose --locked

      - name: Run tests
        run: cargo test --verbose
